# Generated by Django 3.2.6 on 2022-07-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220625_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='PurchaseRequestRequestedUser',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='PurchaseRequestStatus',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseStatus', models.IntegerField(blank=True, choices=[(1, 'درخواست شده'), (2, 'متوقف'), (4, 'تخصیص داده شده'), (5, 'باز'), (6, 'در حال پیشرفت'), (7, 'بسته شده کامل'), (8, 'بسته شده، ناقص'), (9, 'در انتظار قطعه')], null=True, verbose_name='وضعیت درخواست')),
                ('PurchaseDateTo', models.DateField(blank=True, null=True, verbose_name='مهلت تا تاریخ')),
                ('PurchaseDateFrom', models.DateField(verbose_name='تاریخ درخواست')),
                ('PurchaseRequestedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseRequestdUser', to='myapp.sysuser', verbose_name='کاربر درخواست کننده')),
                ('PurchaseTayeedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseAdmitter', to='myapp.sysuser', verbose_name='کاربر تایید کننده')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
