# Generated by Django 3.2.6 on 2022-07-16 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_purchaserequest_purchaserequestpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='PurchaseDateFrom',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestDateFrom',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ درخواست'),
        ),
    ]
