# Generated by Django 3.2.6 on 2022-07-18 15:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220716_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='PurchaseDateFrom',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='PurchaseRequestDateFrom',
        ),
        migrations.AddField(
            model_name='purchase',
            name='PurchaseCompletionDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='PurchaseDateTo',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاریخ '),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='PurchaseRequestDateTo',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='مهلت تا تاریخ'),
            preserve_default=False,
        ),
    ]
