# Generated by Django 3.2.6 on 2022-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220718_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='PurchaseDateTo',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ '),
        ),
    ]
