# Generated by Django 3.2.6 on 2022-07-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_purchase_purchasedateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='PurchaseTayeedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseAdmitter', to='myapp.sysuser', verbose_name='کاربر تایید کننده'),
        ),
    ]
