# Generated by Django 3.2.6 on 2022-08-01 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_purchase_purchasetayeeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warantyType', models.IntegerField(blank=True, choices=[(1, 'ساده'), (2, 'قابل تمدید')], null=True, verbose_name='نوع گارانتی')),
                ('warantyUsageTermType', models.IntegerField(blank=True, choices=[(1, 'تاریخ'), (2, 'اندازه گیری'), (3, 'ساعت تولید')], null=True, verbose_name='شرایط استفاده از گارانتی')),
                ('warantyDataAdded', models.DateField(auto_now_add=True, verbose_name=' تاریخ  ثبت')),
                ('warantyExpirationDate', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انقضا')),
                ('warantyQnty', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('warantyMeterReadingValueLimit', models.IntegerField(blank=True, null=True, verbose_name='مقدار محدودکننده؟؟؟')),
                ('warantyMeterReadingUnit', models.IntegerField(blank=True, choices=[(1, 'Cycles (cycles)'), (2, 'Cycles (g)'), (3, 'Hours (h)'), (4, 'Kilometers (km)'), (5, 'Kilopascals (kPa)'), (6, 'Litres (l)'), (7, 'Meters (m)'), (8, 'Miles (mi)'), (9, 'Pounds per square inch (PSI)'), (10, 'ProductionHours (ph)'), (11, 'Revolutions (rev)')], null=True, verbose_name='واحد اندازه گیری')),
                ('warantyCertificationNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره گواهی')),
                ('warantyDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('warantyLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.asset', verbose_name='مکان')),
                ('warantyProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.business', verbose_name='تامین کننده')),
            ],
            options={
                'db_table': 'waranty',
            },
        ),
        migrations.CreateModel(
            name='PartWaranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warantyType', models.IntegerField(blank=True, choices=[(1, 'ساده'), (2, 'قابل تمدید')], null=True, verbose_name='نوع گارانتی')),
                ('warantyUsageTermType', models.IntegerField(blank=True, choices=[(1, 'تاریخ'), (2, 'اندازه گیری'), (3, 'ساعت تولید')], null=True, verbose_name='شرایط استفاده از گارانتی')),
                ('warantyDataAdded', models.DateField(auto_now_add=True, verbose_name=' تاریخ  ثبت')),
                ('warantyExpirationDate', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='تاریخ انقضا')),
                ('warantyQnty', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('warantyMeterReadingValueLimit', models.IntegerField(blank=True, null=True, verbose_name='مقدار محدودکننده؟؟؟')),
                ('warantyMeterReadingUnit', models.IntegerField(blank=True, choices=[(1, 'Cycles (cycles)'), (2, 'Cycles (g)'), (3, 'Hours (h)'), (4, 'Kilometers (km)'), (5, 'Kilopascals (kPa)'), (6, 'Litres (l)'), (7, 'Meters (m)'), (8, 'Miles (mi)'), (9, 'Pounds per square inch (PSI)'), (10, 'ProductionHours (ph)'), (11, 'Revolutions (rev)')], null=True, verbose_name='واحد اندازه گیری')),
                ('warantyCertificationNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره گواهی')),
                ('warantyDescription', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('warantyProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.business', verbose_name='تامین کننده')),
                ('warantyStockItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.part', verbose_name='نام قطعه')),
            ],
            options={
                'db_table': 'partwaranty',
            },
        ),
    ]
