# Generated by Django 3.2.6 on 2023-01-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20230110_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ('-id',)},
        ),
    ]
