# Generated by Django 3.2.6 on 2023-05-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_purchaserequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.business'),
        ),
    ]
