# Generated by Django 3.2.6 on 2023-05-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_purchaserequest_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ('-id',), 'permissions': [('change_request_status', 'Can change the status of purchase request status')]},
        ),
    ]
