# Generated by Django 3.2.6 on 2024-05-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_purchaserequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetTavali',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره توالی'),
        ),
        migrations.CreateModel(
            name='MachineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('description', models.CharField(max_length=50, verbose_name='توضیحات')),
                ('isPartOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.machinecategory', verbose_name='زیر مجموعه')),
            ],
            options={
                'db_table': 'machinecategory',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='assetMachineCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.machinecategory', verbose_name='نوع دستگاه'),
        ),
    ]
