# Generated by Django 3.2.6 on 2024-05-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20240512_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'ordering': (['title'],), 'permissions': (('can_change_status', 'Can change Status'),)},
        ),
    ]
