# Generated by Django 3.2.6 on 2024-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_sysuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysuser',
            options={'permissions': (('can_change_status', 'Can change Status'),)},
        ),
        migrations.AlterModelTable(
            name='sysuser',
            table=('sysusers',),
        ),
    ]
