from myapp.views.userview import *
from myapp.views.dashboardview import *
from myapp.views.folderview import *
from myapp.views.mailview import *
from myapp.views.mailfileview import *
from myapp.views.purchaserequestview import *
from myapp.views.partview import *
from myapp.views.assetview import *
from myapp.views.assetcategoryview import *
from myapp.views.businessview import *
from myapp.views.businessfileview import *
from myapp.views.businessassetview import *
from myapp.views.businesspartview import *
from myapp.views.planningboardview import *
from myapp.views.partcategoryview import *
