from myapp.views.userview import *
from myapp.views.dashboardview import *
from myapp.views.folderview import *
from myapp.views.mailview import *
from myapp.views.mailfileview import *
from myapp.views.purchaserequestview import *
from myapp.views.partview import *
from myapp.views.assetview import *
from cmms.views.businessview import *
from cmms.views.businessfileview import *
from cmms.views.businessassetview import *
from cmms.views.businesspartview import *
